@hostAddress = http://localhost:5097

# Testing the GetExchangeRates method
GET {{hostAddress}}/api/nbp/exchange-rates
Accept: application/json

###

# Testing the GetExchangeRate method for currency code USD
GET {{hostAddress}}/api/nbp/exchange-rate/USD
Accept: application/json

###

# Testing the GetExchangeRate method for currency code EUR
GET {{hostAddress}}/api/nbp/exchange-rate/EUR
Accept: application/json

###
